### ISSUE TITLE
make regression test cluster id unique per run to avoid name collisions

### ISSUE THREAD

**Issue by qrkourier** [netfoundry/ziti-k8s-agent#16]

**Comment by dariuszSki** [comment]
Perhaps we can limit the concurrency across the repo to limit one at a time for PR regression test. 

i.e 
concurrency:
  group: ${{ github.workflow }} 
  cancel-in-progress: true

**Comment by qrkourier** [comment]
Concurrency groups are still a good idea for efficiency of time and resources, but it may not prevent cluster name collisions in GKE or EKS because the name may not be released during teardown before the next job attempts to use it.

**Comment by qrkourier** [comment]
That is, we'd want to write the regression test so that teardown continues when a concurrency constraint cancels the job, and the next job will start running before the teardown completes.

**Comment by dariuszSki** [comment]
Yeah, we need to come up with more efficient way to have the multiple regression tests at one time. Perhaps a combination of  more than one way.

**Comment by qrkourier** [comment]
We have a useful reference in the Fablab jobs which must continue with a long-running teardown even if canceled, and always have run-specific IDs.

**Comment by qrkourier** [comment]
Here's the interesting part of that workflow.

```yaml
  fablab-smoketest-teardown:
    name: Teardown SmokeTest
    # ensure reasonable timeout-minutes on steps in this un-cancellable job
    if: always()
    runs-on: ubuntu-20.04
    needs: [ fablab-smoketest ]
    steps:
      # release cloud resources if the smoketest succeeded, failed, or was cancelled; unnecessary if skipped
      - name: Teardown Test Environment
      # ...
```
