### ISSUE TITLE
default roles

### ISSUE THREAD

**Issue by qrkourier** [netfoundry/ziti-k8s-agent#38]
Support a default role per agent and namespace, replacing the current convention of granting a Ziti role based on a pod app name label.

e.g.,

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace
  labels:
    tunnel.openziti.io/enabled: "true"
  annotations:
    identity.openziti.io/role-attributes: logstash-clients
```

Precedence:

1. pod roles
2. namespace roles
3. agent roles
4. no roles granted - should this eject the pod since there's no possibility the sidecar will do anything?
